name: BetterProtected
main: com.tmc.BetterProtected.BetterProtectedPluginerProtectedPlugin
version: 0.01

#commands:
#  quit:
#    description: This command kicks you from the server.
#    permissions: SelfKick.quit
#    usage: /quit