name: BetterProtected
main: tmc.BetterProtected.BetterProtectedPlugin
version: 0.2

commands:
  transform:
    description: Transform your banana protect files into MongoDB.
    permissions: BetterProtected.transform
    usage: /<command> [world_name]