name: BetterProtected
main: com.tmc.BetterProtected.BetterProtectedPluginerProtectedPlugin
version: 0.01

commands:
  transform:
    description: Transform your banana protect files into MongoDB.
    permissions: BetterProtected.transform
    usage: /<command> [world_name]